-- Sequences for auto-incrementing IDs
CREATE SEQUENCE A_USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE A_ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE A_PERMISSIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CUSTOMER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tables
CREATE TABLE CUSTOMER (
                          ID NUMBER PRIMARY KEY,
                          NAME VARCHAR2(100) NOT NULL,
                          ADDRESS VARCHAR2(200),
                          MOBILE_NO VARCHAR2(20)
                          NID VARCHAR2(20)
);

CREATE TABLE ACCOUNT (
                         ID NUMBER PRIMARY KEY,
                         CUSTOMER_ID NUMBER NOT NULL REFERENCES CUSTOMER(ID),
                         ACCOUNT_NUMBER VARCHAR2(20) UNIQUE NOT NULL,
                         ACCOUNT_TYPE VARCHAR2(10) CHECK (ACCOUNT_TYPE IN ('Savings', 'Current')) NOT NULL,
                         BALANCE NUMBER(15, 2) DEFAULT 0 NOT NULL,
                         STATUS VARCHAR2(10) CHECK (STATUS IN ('Active', 'Inactive')) DEFAULT 'Active' NOT NULL
);

CREATE TABLE TRANSACTION (
                             ID NUMBER PRIMARY KEY,
                             ACCOUNT_ID NUMBER NOT NULL REFERENCES ACCOUNT(ID),
                             TYPE VARCHAR2(10) CHECK (TYPE IN ('Deposit', 'Withdrawal', 'Transfer')) NOT NULL,
                             AMOUNT NUMBER(15, 2) NOT NULL,
                             TRANSACTION_DATE DATE DEFAULT SYSDATE NOT NULL,
                             REFERENCE VARCHAR2(50) UNIQUE NOT NULL,
                             FROM_ACCOUNT_ID NUMBER REFERENCES ACCOUNT(ID),
                             TO_ACCOUNT_ID NUMBER REFERENCES ACCOUNT(ID),
                             REMARKS VARCHAR2(200)
);

-- Indexes
CREATE INDEX IDX_ACCOUNT_NUMBER ON ACCOUNT(ACCOUNT_NUMBER);
CREATE INDEX IDX_TRANSACTION_DATE ON TRANSACTION(TRANSACTION_DATE);

-- Triggers for auto-incrementing IDs

CREATE OR REPLACE TRIGGER TRANSACTION_TRG
BEFORE INSERT ON TRANSACTION
FOR EACH ROW
BEGIN
    :NEW.ID := TRANSACTION_SEQ.NEXTVAL;
    :NEW.REFERENCE := 'TXN-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-' || TRANSACTION_SEQ.CURRVAL;
END;


