
CREATE SEQUENCE A_USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE A_ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE A_PERMISSIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CUSTOMER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE A_ROLES (
                         ID NUMBER(19,0),
                         NAME VARCHAR2(255),
                         CONSTRAINT SYS_C008881 CHECK ("ID" IS NOT NULL),
                         CONSTRAINT SYS_C008882 CHECK ("NAME" IS NOT NULL),
                         CONSTRAINT SYS_C008883 PRIMARY KEY (ID),
                         CONSTRAINT UKIN5FDXOR4M7OFLGDCYQ1OB2I4 UNIQUE (NAME)
);

CREATE UNIQUE INDEX SYS_C008883 ON A_ROLES (ID);
CREATE UNIQUE INDEX UKIN5FDXOR4M7OFLGDCYQ1OB2I4 ON A_ROLES (NAME);


CREATE TABLE A_PERMISSIONS (
                                       ID NUMBER(19,0),
                                       NAME VARCHAR2(255),
                                       CONSTRAINT SYS_C008877 CHECK ("ID" IS NOT NULL),
                                       CONSTRAINT SYS_C008878 PRIMARY KEY (ID),
                                       CONSTRAINT UK9F9J7NF1RPYV6WK2DK3O8G5FD UNIQUE (NAME)
);
CREATE UNIQUE INDEX SYS_C008878 ON A_PERMISSIONS (ID);
CREATE UNIQUE INDEX UK9F9J7NF1RPYV6WK2DK3O8G5FD ON A_PERMISSIONS (NAME);

CREATE TABLE A_USERS (
                                 ID NUMBER(19,0),
                                 DEPT VARCHAR2(255),
                                 EMAIL VARCHAR2(255),
                                 EMPLOYEE_ID VARCHAR2(255),
                                 MOBILE_NO VARCHAR2(255),
                                 PASSWORD VARCHAR2(255),
                                 STATUS VARCHAR2(255),
                                 USERNAME VARCHAR2(255),
                                 CONSTRAINT SYS_C008912 CHECK ("ID" IS NOT NULL),
                                 CONSTRAINT SYS_C008913 CHECK ("EMAIL" IS NOT NULL),
                                 CONSTRAINT SYS_C008914 CHECK ("USERNAME" IS NOT NULL),
                                 CONSTRAINT SYS_C008915 CHECK ((status in ('ACTIVE','APPROVED','DELETED','DORMANT','INACTIVE','PENDING'))),
                                 CONSTRAINT SYS_C008916 PRIMARY KEY (ID),
                                 CONSTRAINT UK3VJ9CYTXAPPYY0DHR4CPOVBGN UNIQUE (MOBILE_NO),
                                 CONSTRAINT UKAQHPTT8HK7TJ56J2N31LCXPR8 UNIQUE (EMAIL),
                                 CONSTRAINT UKEQ7Q2LLJTWDR5WGTNPSWC5DJF UNIQUE (USERNAME)
);
CREATE UNIQUE INDEX SYS_C008916 ON A_USERS (ID);
CREATE UNIQUE INDEX UK3VJ9CYTXAPPYY0DHR4CPOVBGN ON A_USERS (MOBILE_NO);
CREATE UNIQUE INDEX UKAQHPTT8HK7TJ56J2N31LCXPR8 ON A_USERS (EMAIL);
CREATE UNIQUE INDEX UKEQ7Q2LLJTWDR5WGTNPSWC5DJF ON A_USERS (USERNAME);


CREATE TABLE A_ROLE_PERMISSIONS
(	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
     "PERMISSION_ID" NUMBER(19,0) NOT NULL ENABLE
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


ALTER TABLE A_ROLE_PERMISSIONS ADD CONSTRAINT "FK4LGRNJGC2W9J4S9LRTQYWROFJ" FOREIGN KEY ("PERMISSION_ID")
    REFERENCES "A_PERMISSIONS" ("ID") ENABLE;
ALTER TABLE A_ROLE_PERMISSIONS ADD CONSTRAINT "FKSAW5R3F3820YI5CHM6TVYYGB1" FOREIGN KEY ("ROLE_ID")
    REFERENCES "A_ROLES" ("ID") ENABLE;

CREATE TABLE A_USER_ROLES
(	"USER_ID" NUMBER(19,0) NOT NULL ENABLE,
     "ROLE_ID" NUMBER(19,0) NOT NULL ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



ALTER TABLE A_USER_ROLES ADD CONSTRAINT "FK9T9VANJV0UGOA7YE9TO0A7D0W" FOREIGN KEY ("ROLE_ID")
    REFERENCES A_ROLES ("ID") ENABLE;
ALTER TABLE A_USER_ROLES ADD CONSTRAINT "FKCCSRY19XSHFDXLTUDRCD4T3AG" FOREIGN KEY ("USER_ID")
    REFERENCES A_USERS ("ID") ENABLE;

CREATE TABLE CUSTOMER (
                                  ID NUMBER(19,0),
                                  ADDRESS VARCHAR2(255),
                                  NAME VARCHAR2(255),
                                  MOBILE_NO VARCHAR2(255),
                                  NID VARCHAR2(255),
                                  GENDER VARCHAR2(255),
                                  CONSTRAINT SYS_C008894 CHECK ("ID" IS NOT NULL),
                                  CONSTRAINT SYS_C008895 PRIMARY KEY (ID),
                                  CONSTRAINT SYS_C008929 CHECK ((gender in ('MALE','FEMALE')))
);
CREATE UNIQUE INDEX SYS_C008895 ON CUSTOMER (ID);


CREATE TABLE ACCOUNT (
                                 ID NUMBER(19,0),
                                 ACCOUNT_NUMBER VARCHAR2(255),
                                 ACCOUNT_TYPE VARCHAR2(255),
                                 BALANCE BINARY_DOUBLE,
                                 STATUS VARCHAR2(255),
                                 CUSTOMER_ID NUMBER(19,0),
                                 DAILY_TRANSACTION_LIMIT BINARY_DOUBLE,
                                 CONSTRAINT SYS_C008891 CHECK ("ID" IS NOT NULL),
                                 CONSTRAINT SYS_C008892 CHECK ("BALANCE" IS NOT NULL),
                                 CONSTRAINT SYS_C008893 PRIMARY KEY (ID)
);
CREATE INDEX IDX_ACCOUNT_AC_NO ON ACCOUNT (ACCOUNT_NUMBER);
CREATE UNIQUE INDEX SYS_C008893 ON ACCOUNT (ID);



ALTER TABLE ACCOUNT ADD CONSTRAINT "FKNNWPO0LFQ4XAI1RS6887SX02K" FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES CUSTOMER ("ID") ENABLE;

CREATE TABLE TRANSACTION (
                                       ID NUMBER(19,0),
                                       AMOUNT BINARY_DOUBLE,
                                       REFERENCE VARCHAR2(255),
                                       REMARKS VARCHAR2(255),
                                       FROM_ACCOUNT_ID NUMBER(19,0),
                                       TO_ACCOUNT_ID NUMBER(19,0),
                                       FROM_AC_RUNNING_BALANCE BINARY_DOUBLE,
                                       TO_AC_RUNNING_BALANCE BINARY_DOUBLE,
                                       TRANSACTION_DATE TIMESTAMP,
                                       TRANSACTION_TYPE VARCHAR2(255),
                                       CONSTRAINT SYS_C008896 CHECK ("ID" IS NOT NULL),
                                       CONSTRAINT SYS_C008897 CHECK ("AMOUNT" IS NOT NULL),
                                       CONSTRAINT SYS_C008898 PRIMARY KEY (ID),
                                       CONSTRAINT SYS_C008924 CHECK ("TRANSACTION_TYPE"='DEPOSIT' OR "TRANSACTION_TYPE"='WITHDRAWAL' OR "TRANSACTION_TYPE"='ACCOUNT_TRANSFER')
);
CREATE INDEX IDX_TRANSACTION_TRX_DATE_ ON "TRANSACTION" (TRANSACTION_DATE);
CREATE UNIQUE INDEX SYS_C008898 ON "TRANSACTION" (ID);




ALTER TABLE TRANSACTION ADD CONSTRAINT "FKRFF4JLXETAFJU1E5CKS5MFCNK" FOREIGN KEY ("FROM_ACCOUNT_ID")
    REFERENCES ACCOUNT ("ID") ENABLE;
ALTER TABLE TRANSACTION ADD CONSTRAINT "FKLUQT8K2PA8D4GMGGX4RHL5VGV" FOREIGN KEY ("TO_ACCOUNT_ID")
    REFERENCES ACCOUNT ("ID") ENABLE;

INSERT INTO A_ROLES(ID, NAME) VALUES(1, 'ADMIN');

INSERT INTO A_USERS
(ID, DEPT, EMAIL, EMPLOYEE_ID, MOBILE_NO, PASSWORD, STATUS, USERNAME)
VALUES(1, 'admin', 'admin@gmail.com', 'ncc26', '017101234564',
       '$2a$10$hDE6Yeeq1uIMu.wakIiENu5W7eWXVazeHveBm8S/ini9QVwOtIFUe', 'ACTIVE', 'admin');
INSERT INTO A_USER_ROLES(USER_ID, ROLE_ID) VALUES (1, 1);