spring.application.name=bank-cbs
server.servlet.context-path=/cbs
server.port=8080
#ORACLE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/TEST_BANK
spring.datasource.username=appuser
spring.datasource.password=appuser123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.properties.hibernate.transaction.coordinator_class= jdbc

# JWT config
jwt.secretKey=pZxk8vN2q4dF3tR0sV7yJ9wQh2ZfD3LmT8Kb1uY5xCr0ePq9sXn4mVt6rAq2Hj8P
jwt.accessTokenExpirationMinutes=15
jwt.refreshTokenExpirationDays=30

#spring.sql.init.mode=always
#spring.sql.init.encoding=UTF-8
#spring.sql.init.continue-on-error=true
#spring.sql.init.schema-locations=classpath:/DB_FILES/InitialScript.sql
#spring.sql.init.data-locations=classpath:/db/data.sql

cbs.dailyTransactionLimit=10000